function cellInfo = Bus(varargin) 
% BUS returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'EgoVehiclePoseBus', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'ActorID', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Position', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Velocity', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Roll', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pitch', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Yaw', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'AngularVelocity', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'EgoVehicleStateBus', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'Position', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Velocity', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Orientation', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'AngularVelocity', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Acceleration', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
